global:
  scrape_interval: 6h
  evaluation_interval: 6h

scrape_configs:
  - job_name: "gamemetrics_api"
    static_configs:
      - targets: ["api:5000"]
    metrics_path: "/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
