apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgresql
    url: gamemetrics_db:5432
    database: gamemetrics
    user: gamemetrics
    secureJsonData:
      password: "gamemetrics_secret"
    jsonData:
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
